name: Run Scraper

on:
  workflow_dispatch:  # Permite execução manual

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Substitua pela versão do Node.js que você está usando

      - name: Install dependencies
        run: npm install

      - name: Run scraper
        run: npm start
